-- MySQL Script generated by MySQL Workbench
-- Mon Apr 10 12:50:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `pk_usuario` INT(20) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `matricula` INT(40) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pk_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proposta` (
  `pk_proposta` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `fk_usuario` INT(20) NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`pk_proposta`, `fk_usuario`),
  INDEX `fk_Proposta_usuario_idx` (`fk_usuario` ASC),
  CONSTRAINT `fk_Proposta_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`usuario` (`pk_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `pk_equipe` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pk_equipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membro` (
  `pk_membro` INT NOT NULL AUTO_INCREMENT,
  `atuacao` VARCHAR(255) NOT NULL,
  `nivel` VARCHAR(255) NOT NULL,
  `fk_equipe` INT NOT NULL,
  `funcao` VARCHAR(50) NOT NULL,
  `fk_usuario` INT(20) NOT NULL,
  `carga` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`pk_membro`, `fk_equipe`, `fk_usuario`),
  INDEX `fk_programador_equipe1_idx` (`fk_equipe` ASC),
  INDEX `fk_membro_usuario1_idx` (`fk_usuario` ASC),
  CONSTRAINT `fk_programador_equipe1`
    FOREIGN KEY (`fk_equipe`)
    REFERENCES `mydb`.`equipe` (`pk_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membro_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`usuario` (`pk_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projeto` (
  `fk_equipe` INT NOT NULL,
  `fk_proposta` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`fk_equipe`, `fk_proposta`),
  INDEX `fk_equipe_has_proposta_proposta1_idx` (`fk_proposta` ASC),
  INDEX `fk_equipe_has_proposta_equipe1_idx` (`fk_equipe` ASC),
  CONSTRAINT `fk_equipe_has_proposta_equipe1`
    FOREIGN KEY (`fk_equipe`)
    REFERENCES `mydb`.`equipe` (`pk_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_has_proposta_proposta1`
    FOREIGN KEY (`fk_proposta`)
    REFERENCES `mydb`.`proposta` (`pk_proposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`voto` (
  `pk_voto` INT NOT NULL,
  `contagem` INT(11) NOT NULL,
  `fk_usuario` INT(20) NOT NULL,
  `fk_proposta` INT NOT NULL,
  PRIMARY KEY (`pk_voto`, `fk_usuario`, `fk_proposta`),
  INDEX `fk_voto_usuario1_idx` (`fk_usuario` ASC),
  INDEX `fk_voto_proposta1_idx` (`fk_proposta` ASC),
  CONSTRAINT `fk_voto_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`usuario` (`pk_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voto_proposta1`
    FOREIGN KEY (`fk_proposta`)
    REFERENCES `mydb`.`proposta` (`pk_proposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
